AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'tmp/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
